LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)


LOCAL_C_INCLUDES += $(LOCAL_PATH)/../include

LOCAL_SRC_FILES := \
    ../src/aes/stub.c \
    ../src/base64/b64.c \
    ../src/bfcp/attr.c \
    ../src/bfcp/conn.c \
    ../src/bfcp/msg.c \
    ../src/bfcp/reply.c \
    ../src/bfcp/request.c \
    ../src/conf/conf.c \
    ../src/crc32/crc32.c \
    ../src/dbg/dbg.c \
    ../src/dns/client.c \
    ../src/dns/cstr.c \
    ../src/dns/dname.c \
    ../src/dns/hdr.c \
    ../src/dns/ns.c \
    ../src/dns/rr.c \
    ../src/dns/rrlist.c \
    ../src/fmt/ch.c \
    ../src/fmt/hexdump.c \
    ../src/fmt/pl.c \
    ../src/fmt/print.c \
    ../src/fmt/prm.c \
    ../src/fmt/regex.c \
    ../src/fmt/str.c \
    ../src/fmt/str_error.c \
    ../src/fmt/time.c \
    ../src/hash/func.c \
    ../src/hash/hash.c \
    ../src/httpauth/basic.c \
    ../src/http/auth.c \
    ../src/httpauth/digest.c \
    ../src/http/client.c \
    ../src/http/msg.c \
    ../src/http/server.c \
    ../src/ice/cand.c \
    ../src/ice/candpair.c \
    ../src/ice/chklist.c \
    ../src/ice/comp.c \
    ../src/ice/connchk.c \
    ../src/ice/gather.c \
    ../src/ice/ice.c \
    ../src/ice/icem.c \
    ../src/ice/icesdp.c \
    ../src/ice/icestr.c \
    ../src/ice/stunsrv.c \
    ../src/ice/util.c \
    ../src/jbuf/jbuf.c \
    ../src/list/list.c \
    ../src/lock/lock.c \
    ../src/main/epoll.c \
    ../src/main/init.c \
    ../src/main/main.c \
    ../src/main/method.c \
    ../src/mbuf/mbuf.c \
    ../src/mem/mem.c \
    ../src/mod/dl.c \
    ../src/mod/mod.c \
    ../src/mqueue/mqueue.c \
    ../src/msg/ctype.c \
    ../src/msg/param.c \
    ../src/natbd/filtering.c \
    ../src/natbd/genalg.c \
    ../src/natbd/hairpinning.c \
    ../src/natbd/lifetime.c \
    ../src/natbd/mapping.c \
    ../src/natbd/natstr.c \
    ../src/net/if.c \
    ../src/net/net.c \
    ../src/net/netstr.c \
    ../src/net/rt.c \
    ../src/net/sock.c \
    ../src/net/sockopt.c \
    ../src/rtp/fb.c \
    ../src/rtp/member.c \
    ../src/rtp/ntp.c \
    ../src/rtp/pkt.c \
    ../src/rtp/rr.c \
    ../src/rtp/rtcp.c \
    ../src/rtp/rtp.c \
    ../src/rtp/sdes.c \
    ../src/rtp/sess.c \
    ../src/rtp/source.c \
    ../src/sa/ntop.c \
    ../src/sa/printaddr.c \
    ../src/sa/pton.c \
    ../src/sa/sa.c \
    ../src/sdp/attr.c \
    ../src/sdp/format.c \
    ../src/sdp/media.c \
    ../src/sdp/msg.c \
    ../src/sdp/session.c \
    ../src/sdp/str.c \
    ../src/sip/addr.c \
    ../src/sip/auth.c \
    ../src/sip/cseq.c \
    ../src/sip/ctrans.c \
    ../src/sip/dialog.c \
    ../src/sip/contact.c \
    ../src/sipevent/listen.c \
    ../src/sipevent/msg.c \
    ../src/sipevent/notify.c \
    ../src/sipevent/subscribe.c \
    ../src/sip/keepalive.c \
    ../src/sip/keepalive_udp.c \
    ../src/sip/msg.c \
    ../src/sipreg/reg.c \
    ../src/sip/reply.c \
    ../src/sip/request.c \
    ../src/sipsess/accept.c \
    ../src/sipsess/ack.c \
    ../src/sipsess/close.c \
    ../src/sipsess/connect.c \
    ../src/sipsess/info.c \
    ../src/sipsess/listen.c \
    ../src/sipsess/modify.c \
    ../src/sipsess/reply.c \
    ../src/sipsess/request.c \
    ../src/sipsess/sess.c \
    ../src/sip/sip.c \
    ../src/sip/strans.c \
    ../src/sip/transp.c \
    ../src/sip/via.c \
    ../src/stun/addr.c \
    ../src/stun/attr.c \
    ../src/stun/ctrans.c \
    ../src/stun/dnsdisc.c \
    ../src/stun/hdr.c \
    ../src/stun/ind.c \
    ../src/stun/keepalive.c \
    ../src/stun/msg.c \
    ../src/stun/rep.c \
    ../src/stun/req.c \
    ../src/stun/stun.c \
    ../src/stun/stunstr.c \
    ../src/sys/daemon.c \
    ../src/sys/endian.c \
    ../src/sys/fs.c \
    ../src/sys/rand.c \
    ../src/sys/sleep.c \
    ../src/sys/sys.c \
    ../src/tcp/tcp.c \
    ../src/tcp/tcp_high.c \
    ../src/telev/telev.c \
    ../src/tmr/tmr.c \
    ../src/turn/chan.c \
    ../src/turn/perm.c \
    ../src/turn/turnc.c \
    ../src/udp/mcast.c \
    ../src/udp/udp.c \
    ../src/uri/ucmp.c \
    ../src/uri/uri.c \
    ../src/uri/uric.c \
    ../src/websock/websock.c \
    ../src/md5/md5.c \
    ../src/md5/wrap.c \
    ../src/sha/sha1.c \
    ../src/hmac/hmac.c \
    ../src/hmac/hmac_sha1.c \
    ../src/net/posix/pif.c

LOCAL_MODULE    := libre
LOCAL_MODULE_TAGS := optional

APP_CFLAGS := -DHAVE_PTHREAD=1 \
		-DHAVE_PTHREAD_RWLOCK=1 \
		-DHAVE_POLL \
		-DHAVE_LIBPTHREAD= \
		-DPEDANTIC= \
		-DANDROID=1

LOCAL_CFLAGS := $(APP_CFLAGS)

include $(BUILD_SHARED_LIBRARY)
